// examples/next/app/protected/page.tsx
import Link from "next/link";
import { Suspense } from "react";
import { GlyphScramble } from "@brip/glyphscramble-next";
import { glyphs } from "../../glyphscramble.next";
import { ClonedPayload } from "./cloned-payload";

const FIRST = "Sensitive analyst note alpha.";
const SECOND = "Sensitive analyst note beta.";

async function ProtectedBlocks() {
  const first = await glyphs.scramble(FIRST, { font: "body", lang: "en" });
  const second = await glyphs.scramble(SECOND, { font: "body", lang: "en" });
  return (
    <section aria-label="Demonstration of intentionally inaccessible protected content">
      <ClonedPayload payload={first} />
      <GlyphScramble
        className="protected"
        data-testid="protected-second"
        data-font-url={second.fontUrl}
        payload={second}
      />
    </section>
  );
}

export default function Protected() {
  return (
    <main>
      <nav>
        <Link href="/">Home</Link>
        <Link href="/unprotected">Unprotected example</Link>
      </nav>
      <h1>Protected high-value block fixture</h1>
      <Suspense fallback={<p>Preparing protected content…</p>}>
        <ProtectedBlocks />
      </Suspense>
    </main>
  );
}

// examples/nuxt/app/pages/protected.vue
<script setup lang="ts">
import type { GlyphPayload } from "@brip/glyphscramble";

interface ProtectedPayloads {
  first: GlyphPayload;
  second: GlyphPayload;
}

const { data } = await useAsyncData("protected-payloads", () =>
  $fetch<ProtectedPayloads>("/api/protected"),
);
if (!data.value) throw createError({ statusCode: 503 });
const first = ref(data.value.first);
const second = computed(() => data.value!.second);

async function replacePayload(): Promise<void> {
  const replacement = await $fetch<ProtectedPayloads>("/api/protected");
  first.value = replacement.first;
}
</script>

<template>
  <main>
    <nav>
      <NuxtLink to="/">Home</NuxtLink>
      <NuxtLink to="/unprotected">Unprotected example</NuxtLink>
    </nav>
    <h1>Protected high-value block fixture</h1>
    <section aria-label="Intentionally inaccessible protected content">
      <GlyphScramble
        :payload="first"
        as="span"
        class="protected"
        data-testid="protected-first"
        :data-font-url="first.fontUrl"
        error-text="Protected fixture unavailable."
      />
      <GlyphScramble
        :payload="second"
        as="span"
        class="protected"
        data-testid="protected-second"
        :data-font-url="second.fontUrl"
      />
      <button
        data-testid="replace-payload"
        type="button"
        @click="replacePayload"
      >
        Replace payload
      </button>
    </section>
  </main>
</template>
